name: Cron Job

on:
  schedule:
    # - cron: '*/5 * * * *'
    - cron: '0 10 * * 1-5'


jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Check out code
      uses: actions/checkout@v2 

    - name: Compile all files
      run: javac *.java

      
