name: Use custom-env to Build JAVA 

on:
  push:
    branches:
      - main

env:
  JAVA_VERSION: '17'
  COMPILE_COMMAND: 'javac *.java'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Compile All files
        run: ${{ env.COMPILE_COMMAND }}

      - name: Run Main file
        run: java Main
