name: Build Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu latest
    env:
      COMPILE: *.java
      JAVA_VERSION: 17

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '$JAVA_VERSION'

    - name: Checkout repository
      uses: actions/checkout@v2 

    - name: Compile All files
      run: javac $COMPILE
