name: Using Secret Token to Build JAVA

on:
  push:
    branches:
      - main

jobs:
  Using-Secret-Token:

    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Check out code
      uses: actions/checkout@v2

    # - name: Using Secret Token to compile and run
    - name: Using Secret Token to compile and run
      run: |
        if [ "${{ secrets.USERNAME }}" == "student" ] && [ "${{ secrets.PASSWORD }}" == "student@123" ]; then
          javac *.java
          java Main
        else
          echo "Invalid username or password"
        fi
        
      
    
